name: 2littleducks
favicon: null
layout_spectrum: 0.9870492110494524
typography_spectrum: 0.5862324957270175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6300263323355466
  lightness: 0.11533724144101143
  saturation: 0.3172293184325099
  rhythmicContrast: 0.18156926915980875
purpose: []
