name: 2littleducks
favicon: null
layout_spectrum: 0.9870492110494524
typography_spectrum: 0.174549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#51671E'
    - '#000000'
    - '#98C038'
    - '#C8E098'
  brandStrength: 1
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
