name: 2littleducks
favicon: null
layout_spectrum: 0.9870492110494524
typography_spectrum: 0.4625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9bcb3b'
    - '#010101'
    - '#d0d0d0'
    - '#5d5d5d'
  brandStrength: 1
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
